#include "model/input.h"
#include <solver.h>

Input generate_input()
{
    Input input = {
        .light = REAL(0.0),
        .limitation_of_photosyntetic_rate = REAL(0.5),
        .max_photosyntetic_rate = REAL(12.7),
        .nitrogen_saturation = REAL(0.45),
        .phosphorus_saturation = REAL(0.45),
        .leaf_biomass = REAL(0.02),
        .root_biomass = REAL(0.02),
        .total_biomass = REAL(0.04),
        .min_leaf_biomass = REAL(0.001),
        .feedback_on_photosynthesis = REAL(0.62),
        .max_starch = REAL(10.0),
        .max_starch_degradation_rate = REAL(6.0),
        .photoperiod = REAL(12.0),
        .optimal_stechiometric_ratio = REAL(10.0),
        .starch_partition_coeff = REAL(0.6),
        .starch_degradation_rate = REAL(0.0),
        .uptake_cost = REAL(0.0),
        .transport_cost = REAL(0.0),
        .respiration_frequency = REAL(0.79),
        .sucrose_loading_frequency = REAL(1.98),
        .night_efficiency_starch = REAL(0.5),
        .max_sucrose = REAL(2.0),
        .min_sucrose = REAL(1.3),
        .starch_night_start = REAL(2.0),
        .min_starch = REAL(0.15),
        .lambda_sdr = REAL(0.25),
        .lambda_sdi = REAL(0.10),
        .lambda_sni = REAL(0.08),
        .lambda_g = REAL(0.65),
        .lambda_sb = REAL(0.00587),
        .sucrose = REAL(3.2),
        .starch = REAL(2.0),
        .nitrogen = REAL(30),
        .phosphorus = REAL(3),
        .nitrogen_uptake = REAL(0.0),
        .phosphorus_uptake = REAL(0.0),
        .assimilation_cost_nitrogen = REAL(0.0460308),
        .lambda_csn = REAL(0.0267),
        .min_nitrogen_photosynthesis = REAL(5.75),
        .min_phosphorus_photosynthesis = REAL(0.575),
        .nutrient_conversion_parameter = REAL(0.066),
        .assimilation_cost_phorphorus = REAL(0.00460308),
        .pot_nitrogen_uptake = REAL(0.0),
        .pot_phosphorus_uptake = REAL(0.0),
        .nitrogen_nutrient_uptake = REAL(0.0),
        .phosphorus_nutrient_uptake = REAL(0.0),
        .nitrogen_affinity = REAL(0.5),
        .phosphorus_affinity = REAL(0.5),
        .nitrogen_soil_content = REAL(12.0),
        .phosphorus_soil_content = REAL(0.15),
        .nitrogen_uptake_sucrose_consumption = REAL(0.68),
        .phosphorus_uptake_sucrose_consumption = REAL(0.308),
        .max_nitrogen_uptake = REAL(6.44),
        .max_phosphorus_uptake = REAL(0.4),
        .Michaelis_Menten_constant_nitrogen = REAL(0.125),
        .Michaelis_Menten_constant_phosphorus = REAL(0.006736),
        .lambda_k = REAL(50.0),
        .max_nitrogen = REAL(23.0),
        .min_nitrogen = REAL(5.75),
        .max_phosphorus = REAL(2.3),
        .min_phosphorus = REAL(0.575),
        .nitrogen_cost = REAL(0.0),
        .phosphorus_cost = REAL(0.0),
        .sucrose_consumption_transport = REAL(0.0035),
        .sucrose_root_allocation = REAL(0.5),
        .stochiometric_signal = REAL(0.5),
        .leaf_deathrate = REAL(0.000005),
        .root_deathrate = REAL(0.000005),
        .leaf_competitive_rate = REAL(0.000005),
        .root_competitive_rate = REAL(0.000005),
        // farquhar
        .ambient_CO2_concentration = REAL(400.0),
        .net_photosynthesis_rate = REAL(10.0),
        .stomatal_conductance = REAL(0.1),
        .convert_to_photosynthesis_per_gram_per_hour = REAL(24000.0),
        .specific_leaf_area = REAL(0.025),
        .net_photosynthesis = REAL(10.0),
        .rubisco_limited_rate = REAL(12.0),
        .light_limited_rate = REAL(10.0),
        .respiration_rate = REAL(1.5),
        .light_limited_photosynthesis = REAL(10.0),
        .CO2_compensation_point = REAL(42.0),
        .electron_transport_rate = REAL(90.0),
        .rubisco_limited_photosynthesis = REAL(12.0),
        .max_rubisco_carboxylation_rate = REAL(45.0),
        .michaelis_constant_CO2 = REAL(404.9),
        .michaelis_constant_O2 = REAL(278.4),
        .oxygen_concentration = REAL(210.0),
        // Jarvis
        .leaf_temperature = REAL(25.0),
        .relative_humidity = REAL(60.0),
        .leaf_water_potential = REAL(-0.6),

    };

    return input;
}
