#include "model/input.h"
#include <solver.h>

Input generate_input()
{
    /* TODO: Externalize these defaults into a config file/profile set to avoid recompilation for calibration runs. */
    Input input = {
        .photo.light = REAL(0.0),
        .photo.limitation_of_photosynthetic_rate = REAL(0.5),
        .photo.max_photosynthetic_rate = REAL(12.7),
        .photo.nitrogen_saturation = REAL(0.45),
        .photo.phosphorus_saturation = REAL(0.45),
        .growth.leaf_biomass = REAL(0.02),
        .growth.root_biomass = REAL(0.02),
        .growth.total_biomass = REAL(0.04),
        .photo.min_leaf_biomass = REAL(0.001),
        .photo.feedback_on_photosynthesis = REAL(0.62),
        .carbohydrates.max_starch = REAL(10.0),
        .carbohydrates.max_starch_degradation_rate = REAL(6.0),
        .photo.photoperiod = REAL(12.0),
        .nutrients.optimal_stoichiometric_ratio = REAL(10.0),
        .carbohydrates.starch_partition_coeff = REAL(0.6),
        .carbohydrates.starch_degradation_rate = REAL(0.0),
        .carbohydrates.uptake_cost = REAL(0.0),
        .carbohydrates.transport_cost = REAL(0.0),
        .carbohydrates.respiration_frequency = REAL(0.79),
        .carbohydrates.sucrose_loading_frequency = REAL(1.98),
        .carbohydrates.night_efficiency_starch = REAL(0.5),
        .carbohydrates.max_sucrose = REAL(2.0),
        .carbohydrates.min_sucrose = REAL(1.3),
        .carbohydrates.starch_night_start = REAL(2.0),
        .carbohydrates.min_starch = REAL(0.15),
        .carbohydrates.lambda_sdr = REAL(0.25),
        .carbohydrates.lambda_sdi = REAL(0.10),
        .carbohydrates.lambda_sni = REAL(0.08),
        .carbohydrates.lambda_g = REAL(0.65),
        .growth.lambda_sb = REAL(0.00587),
        .carbohydrates.sucrose = REAL(1.95),
        .carbohydrates.starch = REAL(0.225),
        .nutrients.nitrogen = REAL(8.625),
        .nutrients.phosphorus = REAL(0.8625),
        .nutrients.nitrogen_uptake = REAL(0.0),
        .nutrients.phosphorus_uptake = REAL(0.0),
        .nutrients.assimilation_cost_nitrogen = REAL(0.0460308),
        .nutrients.lambda_csn = REAL(0.0267),
        .nutrients.min_nitrogen_photosynthesis = REAL(5.75),
        .nutrients.min_phosphorus_photosynthesis = REAL(0.575),
        .nutrients.nutrient_conversion_parameter = REAL(0.066),
        .nutrients.assimilation_cost_phosphorus = REAL(0.00460308),
        .nutrients.pot_nitrogen_uptake = REAL(0.0),
        .nutrients.pot_phosphorus_uptake = REAL(0.0),
        .nutrients.nitrogen_nutrient_uptake = REAL(0.0),
        .nutrients.phosphorus_nutrient_uptake = REAL(0.0),
        .nutrients.nitrogen_affinity = REAL(0.5),
        .nutrients.phosphorus_affinity = REAL(0.5),
        .nutrients.nitrogen_soil_content = REAL(15.0),
        .nutrients.phosphorus_soil_content = REAL(0.15),
        .nutrients.nitrogen_uptake_sucrose_consumption = REAL(0.68),
        .nutrients.phosphorus_uptake_sucrose_consumption = REAL(0.308),
        .nutrients.max_nitrogen_uptake = REAL(6.44),
        .nutrients.max_phosphorus_uptake = REAL(0.4),
        .nutrients.Michaelis_Menten_constant_nitrogen = REAL(0.125),
        .nutrients.Michaelis_Menten_constant_phosphorus = REAL(0.006736),
        .nutrients.lambda_k = REAL(50.0),
        .nutrients.max_nitrogen = REAL(23.0),
        .nutrients.min_nitrogen = REAL(5.75),
        .nutrients.max_phosphorus = REAL(2.3),
        .nutrients.min_phosphorus = REAL(0.575),
        .nutrients.nitrogen_cost = REAL(0.0),
        .nutrients.phosphorus_cost = REAL(0.0),
        .carbohydrates.sucrose_consumption_transport = REAL(0.0035),
        .growth.sucrose_root_allocation = REAL(0.5),
        .nutrients.stoichiometric_signal = REAL(0.5),
        .growth.leaf_deathrate = REAL(0.0000005),
        .growth.root_deathrate = REAL(0.0000005),
        .growth.leaf_competitive_rate = REAL(0.0000005),
        .growth.root_competitive_rate = REAL(0.0000005),
        // farquhar
        .gas_exchange.ambient_CO2_concentration = REAL(400.0),
        .gas_exchange.net_photosynthesis_rate = REAL(10.0),
        .gas_exchange.stomatal_conductance = REAL(0.1),
        .gas_exchange.convert_to_photosynthesis_per_gram_per_hour = REAL(24000.0),
        .gas_exchange.specific_leaf_area = REAL(0.025),
        .gas_exchange.net_photosynthesis = REAL(10.0),
        .gas_exchange.rubisco_limited_rate = REAL(12.0),
        .gas_exchange.light_limited_rate = REAL(10.0),
        .gas_exchange.respiration_rate = REAL(1.5),
        .gas_exchange.light_limited_photosynthesis = REAL(10.0),
        .gas_exchange.CO2_compensation_point = REAL(42.0),
        .gas_exchange.electron_transport_rate = REAL(90.0),
        .gas_exchange.rubisco_limited_photosynthesis = REAL(12.0),
        .gas_exchange.max_rubisco_carboxylation_rate = REAL(45.0),
        .gas_exchange.michaelis_constant_CO2 = REAL(404.9),
        .gas_exchange.michaelis_constant_O2 = REAL(278.4),
        .gas_exchange.oxygen_concentration = REAL(210.0),
        // Jarvis
        .gas_exchange.leaf_temperature = REAL(25.0),
        .gas_exchange.relative_humidity = REAL(60.0),
        .gas_exchange.leaf_water_potential = REAL(-0.6),

    };

    return input;
}
