#include "model/input.h"

Input generate_input()
{
    Input input = {
        .light = 0.0f,
        .limitation_of_photosyntetic_rate = 0.5f,
        .max_photosyntetic_rate = 12.7f,
        .nitrogen_saturation = 1.0f,
        .phosphorus_saturation = 1.0f,
        .leaf_biomass = 0.6f,
        .root_biomass = 1.0f,
        .total_biomass = 2.0f,
        .min_leaf_biomass = 0.5f,
        .feedback_on_photosynthesis = 0.62f,
        .max_starch = 72.0f,
        .max_starch_degradation_rate = 6.0f,
        .photoperiod = 12.0f,
        .optimal_stechiometric_ratio = 10.0f,
        .starch_partition_coeff = 0.6f,
        .starch_degradation_rate = 0.0f,
        .uptake_cost = 0.0f,
        .transport_cost = 0.0f,
        .respiration_frequency = 0.79f,
        .sucrose_loading_frequency = 1.98f,
        .night_efficiency_starch = 0.5f,
        .max_sucrose = 2.0f,
        .min_sucrose = 1.3f,
        .starch_night_start = 2.0f,
        .min_starch = 0.15f,
        .lambda_sdr = 0.25f,
        .lambda_sdi = 0.10f,
        .lambda_sni = 0.08f,
        .lambda_g = 0.65f,
        .lambda_sb = 0.00587f,
        .sucrose = 1.5f,
        .starch = 2.0f,
        .nitrogen = 6.5f,
        .phosphorus = 0.65f,
        .nitrogen_uptake = 0.0f,
        .phosphorus_uptake = 0.0f,
        .assimilation_cost_nitrogen = 0.04758f,
        .lambda_csn = 0.0267f,
        .min_nitrogen_photosynthesis = 5.75f,
        .min_phosphorus_photosynthesis = 0.575f,
        .nutrient_conversion_parameter = 0.066f,
        .assimilation_cost_phorphorus = 0.004758f,
        .pot_nitrogen_uptake = 0.0f,
        .pot_phosphorus_uptake = 0.0f,
        .nitrogen_nutrient_uptake = 0.0f,
        .phosphorus_nutrient_uptake = 0.0f,
        .nitrogen_affinity = 0.5f,
        .phosphorus_affinity = 0.5f,
        .nitrogen_soil_content = 15.0f,
        .phosphorus_soil_content = 0.65f,
        .nitrogen_uptake_sucrose_consumption = 0.68f,
        .phosphorus_uptake_sucrose_consumption = 0.308f,
        .max_nitrogen_uptake = 6.44f,
        .max_phosphorus_uptake = 0.4f,
        .Michaelis_Menten_constant_nitrogen = 0.125f,
        .Michaelis_Menten_constant_phosphorus = 0.006736f,
        .lambda_k = 50.0f,
        .max_nitrogen = 23.0f,
        .min_nitrogen = 5.75f,
        .max_phosphorus = 2.3f,
        .min_phosphorus = 0.575f,
        .nitrogen_cost = 0.0f,
        .phosphorus_cost = 0.0f,
        .sucrose_consumption_transport = 0.0035f,
        .sucrose_root_allocation = 0.5f,
        .stochiometric_signal = 0.5f,
        .leaf_deathrate = 0.000005f,
        .root_deathrate = 0.000005f,
        .leaf_competitive_rate = 0.000005f,
        .root_competitive_rate = 0.000005f
    };

    return input;
}
